python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=1 --molecule=H2 > testchemistyH2HE2q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=2 --molecule=H2 > testchemistyH2HEfixedamp2q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=3 --molecule=H2 > testchemistyH2Decay2q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=4 --molecule=H2 > testchemistyH2Decayfixedamp2q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=5 --molecule=H2 > testchemistyH2Dressed2q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=6 --molecule=H2 > testchemistyH2Dressedfixedamp2q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=1 --molecule=LiH > testchemistyLiHHE4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=2 --molecule=LiH > testchemistyLiHHEfixedamp4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=3 --molecule=LiH > testchemistyLiHDecay4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=4 --molecule=LiH > testchemistyLiHDecayfixedamp4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=5 --molecule=LiH > testchemistyLiHDressed4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=chemistry --pulse_id=6 --molecule=LiH > testchemistyLiHDressedfixedamp4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=1 --n_assets=2  > testfinance2assetsHE4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=2 --n_assets=2  > testfinance2assetsHEfixedamp4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=3 --n_assets=2  > testfinance2assetsDecay4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=4 --n_assets=2  > testfinance2assetsDecayfixedamp4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=5 --n_assets=2  > testfinance2assetsDressed4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=6 --n_assets=2  > testfinance2assetsDressedfixedamp4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=1 --n_assets=4  > testfinance4assetsHE4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=2 --n_assets=4  > testfinance4assetsHEfixedamp4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=3 --n_assets=4  > testfinance4assetsDecay4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=4 --n_assets=4  > testfinance4assetsDecayfixedamp4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=5 --n_assets=4  > testfinance4assetsDressed4q.txt&
python -W ignore -u main.py --backend=FakeManila --application=finance --pulse_id=6 --n_assets=4  > testfinance4assetsDressedfixedamp4q.txt&

